name: Update latest tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push for tags matching versioning-pattern
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          description: Nyeste versjon av prinsippene
